// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pim4_FazendaUrbana.WEB.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pim4_FazendaUrbana.DATA.Models;

public partial class Fornecedor
{
    [Key]
    [Column("idFornecedor")]
    public int IdFornecedor { get; set; }

    [Required]
    [Column("razaoSocial")]
    [StringLength(200)]
    public string RazaoSocial { get; set; }

    [Required]
    [Column("nomeFantasia")]
    [StringLength(200)]
    public string NomeFantasia { get; set; }

    [Required]
    [Column("cnpj")]
    [StringLength(30)]
    public string Cnpj { get; set; }

    [Column("dataCadastro", TypeName = "date")]
    public DateTime DataCadastro { get; set; }

    [Column("email")]
    [StringLength(100)]
    public string Email { get; set; }

    

    [InverseProperty("IdFornecedorNavigation")]
    public virtual ICollection<TelefoneFornecedor> TelefoneFornecedor { get; set; } = new List<TelefoneFornecedor>();
}