// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pim4_FazendaUrbana.DATA.Models;

public partial class Plantacao
{
    [Key]
    [Column("idPlantio")]
    public int IdPlantio { get; set; }

    [Required]
    [Column("nomeHortalica")]
    [StringLength(100)]
    public string NomeHortalica { get; set; }

    [Column("dataPlantio", TypeName = "date")]
    public DateTime DataPlantio { get; set; }

    [Column("dataColheita", TypeName = "date")]
    public DateTime DataColheita { get; set; }

    [Column("qtd")]
    public int Qtd { get; set; }

    [Required]
    [Column("status")]
    [StringLength(100)]
    public string Status { get; set; }
}