// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pim4_FazendaUrbana.DATA.Models;

public partial class Produto
{
    [Key]
    [Column("idProduto")]
    public int IdProduto { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(160)]
    public string Nome { get; set; }

    [Column("quantidade")]
    public int Quantidade { get; set; }

    [Column("valorUn", TypeName = "decimal(10, 2)")]
    public decimal ValorUn { get; set; }

    [Required]
    [Column("categoria")]
    [StringLength(150)]
    public string Categoria { get; set; }

    [Column("codigoBarra")]
    [StringLength(100)]
    public string CodigoBarra { get; set; }
}