// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pim4_FazendaUrbana.DATA.Models;

[Table("Telefone_Funcionario")]
public partial class TelefoneFuncionario
{
    [Key]
    [Column("idTelefone")]
    public int IdTelefone { get; set; }

    [Column("idFuncionario")]
    public int IdFuncionario { get; set; }

    [Required]
    [Column("numero")]
    [StringLength(17)]
    public string Numero { get; set; }

    [ForeignKey("IdFuncionario")]
    [InverseProperty("TelefoneFuncionario")]
    public virtual Funcionario IdFuncionarioNavigation { get; set; }
}