// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pim4_FazendaUrbana.DATA.Models;

[Table("Telefone_Fornecedor")]
public partial class TelefoneFornecedor
{
    [Key]
    [Column("idTelefone")]
    public int IdTelefone { get; set; }

    [Column("idFornecedor")]
    public int IdFornecedor { get; set; }

    [Required]
    [Column("numero")]
    [StringLength(20)]
    public string Numero { get; set; }

    [ForeignKey("IdFornecedor")]
    [InverseProperty("TelefoneFornecedor")]
    public virtual Fornecedor IdFornecedorNavigation { get; set; }
}